name: ci
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Check code formatting
        run: cargo fmt --all --check
      - name: Build crate
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  build-msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
      - name: Build crate
        run: cargo build --verbose
